# NumPy Fundamentals for Machile learning and Deep Learning models
# Numerical Python used for efficient numerical computing, especially with arrays and matrices.
Key Uses of Numpy:

1. Multidimensional Arrays ex: np.array
2. Mathematical Operations ex: np.mean(a), np.std(a), np.sum(a)
3. Linear Algebra ex: np.dot(A, B), np.linalg.inv(A)
4. Broadcasting
5. Random Number Generation
6. Fast Iteration & Memory Efficiency (Much faster and more memory-efficient than regular Python lists due to internal C implementation)
7. Data Preparation for ML/AI (Used in machine learning, image processing, signal analysis, etc., for numerical preprocessing before model training)

🔗 Used by Libraries:
Pandas
Scikit-learn
TensorFlow / PyTorch
OpenCV
Matplotlib

In [1]:
import numpy as np

In [28]:
#Array Initialization
A = [1,2,3,4]
B = [1,2,3,4]
linearA = [1,2]
array2d = [[1,2],[3,4]]
array3d = [[[1,2,3],[4,5,6],[7,8,9]]]

In [13]:
dot_product = np.dot(A, B)

In [51]:
print("Dot Product.", dot_product)

Dot Product. 30


In [52]:
C = np.array([[1,2],[3,4]])
print(C.T)

[[1 3]
 [2 4]]


In [53]:
print("Transpose 2d array.", np.transpose(array2d))

Transpose 2d array. [[1 3]
 [2 4]]


In [54]:
print("Matrix Inverse.", np.linalg.inv(array2d))

Matrix Inverse. [[-2.   1. ]
 [ 1.5 -0.5]]


In [55]:
print("Eigen Value and Eigen Vector results.", np.linalg.eig(array2d))

Eigen Value and Eigen Vector results. EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [56]:
print("Solving Linear Systems.", np.linalg.solve(array2, linearA))

Solving Linear Systems. [0.  0.5]


In [ ]:
# 1. Array Creation function

In [57]:
nparray = np.array([1,2,3,4])
print("NP Array.", nparray)

NP Array. [1 2 3 4]


In [58]:
npzero = np.zeros((2,3))
print("2x3 Matrix of Zeroz.", npzero)

2x3 Matrix of Zeroz. [[0. 0. 0.]
 [0. 0. 0.]]


In [59]:
npones = np.ones((3,4))
print("3x4 matrix of ones.", npones)

3x4 matrix of ones. [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [60]:
npeye = np.eye(4)
print("4x4 Identity matrix.", npeye)

4x4 Identity matrix. [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [61]:
npfull = np.full((2,3),5)
print("2x3 Matrix filled with 5.", npfull)

2x3 Matrix filled with 5. [[5 5 5]
 [5 5 5]]


In [62]:
nparange = np.arange(0,10,1)
print("Arrange the n matrix with addition of 1 between 0 to 10.", nparange)

Arrange the n matrix with addition of 1 between 0 to 10. [0 1 2 3 4 5 6 7 8 9]


In [67]:
nplspace = np.linspace(0,100,10)
print("Line space for start, stop and space, (stop-start)/(Space-1).",nplspace)

Line space for start, stop and space, (stop-start)/(Space-1). [  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [82]:
nprandom = np.random.rand(2,2)
print("Random numbers between 0 and 1 for 2x2 matrix with center(mean) 0.5.", nprandom)

Random numbers between 0 and 1 for 2x2 matrix with center(mean) 0.5. [[0.31038807 0.68046006]
 [0.17684643 0.91475354]]


In [83]:
npnrandom = np.random.randn(2,2)
print("Random numbers for 2x2 martrix between -infinity to +infinity with 0 centered(Mean).", npnrandom)

Random numbers for 2x2 martrix between -infinity to +infinity with 0 centered(Mean). [[-0.99960082 -1.3999527 ]
 [-1.40745424  0.48274659]]


In [87]:
npranint = np.random.randint(1,10,(2,2))
print("Random numbers between 0(inclusive) to 10(Exclusive) in 2x2 matrix.",npranint)

Random numbers between 0(inclusive) to 10(Exclusive) in 2x2 matrix. [[8 2]
 [5 8]]


In [ ]:
# 2. Array Manipulation

In [99]:
a = [1,2,3,4,5,6]
reshape = np.reshape(a, (3,2))
print("Reshape the n arrray into 3x3 matrix.", reshape)

Reshape the n arrray into 3x3 matrix. [[1 2]
 [3 4]
 [5 6]]


In [104]:
b = np.ones([2,2])
flatten = np.ravel(b)
print("Flatten any given dimensional array.", flatten)

Flatten any given dimensional array. [1. 1. 1. 1.]


In [107]:
c = [[1,2],[3,4]]
transpose = np.transpose(c)
print("Transpose any given array.", transpose)

Transpose any given array. [[1 3]
 [2 4]]


In [109]:
v1 = [[1,2],[3,4]]
v2 = [[5,6],[7,8]]
vstack = np.vstack([v1,v2])
print("Vertical stacking of two array row wise.",vstack)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [110]:
hstack = np.hstack([v1,v2])
print("Horiontal stacking of two arrays.",hstack)

[[1 2 5 6]
 [3 4 7 8]]


In [115]:
s1 = np.array([1,2,3,4,5,6])
split = np.split(s1, 3)
print("Split array s1 into 3 equal parts.", split)

Split array s1 into 3 equal parts. [array([1, 2]), array([3, 4]), array([5, 6])]


In [120]:
c1 = np.array([1,2,3])
c2 = np.array([4,5,6])
concat = np.concatenate([c1, c2], axis=0)
print("Join the arrays end to end.",concat)

Join the arrays end to end. [1 2 3 4 5 6]


In [134]:
dimension = np.expand_dims(c1, axis=0)
print("New dimsnsion:\n",c1)
print("Shape Comparision before and After:",c1.shape, dimension.shape)

New dimsnsion:
 [1 2 3]
Shape Comparision before and After: (3,) (1, 3)


In [135]:
squeeze = np.squeeze(dimension)
print("Squeezed Dimension.", squeeze)
print("Shape Comparision before and After:",dimension.shape, squeeze.shape)

Squeezed Dimension. [1 2 3]
Shape Comparision before and After: (1, 3) (3,)


In [ ]:
# 3. Mathematical Operations

In [137]:
addition = np.add(A,B)
print("Addition of given Array.",addition)

[2 4 6 8]


In [138]:
subtract = np.subtract(A,B)
print("Subtract Given array.", subtract)


Subtract Given array. [0 0 0 0]


In [143]:
multiply = np.multiply(array2d,array2d)
print("Multiply given Array.", multiply)

Multiply given Array. [[ 1  4]
 [ 9 16]]


In [142]:
div = np.divide(A,B)
print("Divide given Array.", div)

Divide given Array. [1. 1. 1. 1.]


In [144]:
dot_matrix = np.dot(array2d, array2d)
print("Dot Matrix Multiplication.", dot_matrix)

Dot Matrix Multiplication. [[ 7 10]
 [15 22]]


In [148]:
dot1 = np.array([[1,2],[3,4]])
dot2 = np.array([[5,6],[7,8]])
dot_mat = np.dot(dot1,dot2)
print("Dot matrix multiplication of A row and B column.", dot_mat)

Dot matrix multiplication of A row and B column. [[19 22]
 [43 50]]


In [160]:
am = np.random.rand(2,3,4)
bm = np.random.rand(2,4,5)
print("Matrix Multiplication of given array.", np.matmul(am,bm))
print("Shape of Matrix Multiplication of given array.", np.matmul(am,bm).shape)

Matrix Multiplication of given array. [[[0.96865346 0.6496102  0.87589316 1.23773282 1.35060505]
  [0.85034895 1.06940388 0.46026764 0.55346909 1.37378016]
  [1.1438544  1.08302226 0.83140353 1.21301432 1.68457261]]

 [[0.72287633 1.22292159 1.09880467 0.67599629 1.38244865]
  [0.2989648  0.79763067 0.62461835 0.44835778 0.85895302]
  [1.02393256 1.15058851 0.7548284  0.77158118 1.00246876]]]
Shape of Matrix Multiplication of given array. (2, 3, 5)


In [161]:
pow1 = [[1,2],[3,4]]
square = np.power(pow1, 2)
print("Square of given array.", square)

Square of given array. [[ 1  4]
 [ 9 16]]


In [162]:
expo = np.exp(pow1)
print("Exponential calculation on given array.",expo)

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


In [164]:
log1 = np.log(pow1)
print("Log operation on given array.",log1)

Log operation on given array. [[0.         0.69314718]
 [1.09861229 1.38629436]]


In [ ]:
# 4. Trignometric Operations

In [167]:
x1 = [[1,2],[3,4]]
x2 = [[5,6],[7,8]]
sin = np.sin(x1)
cos = np.cos(x1)
tan = np.tan(x1)
print("Trignometric Operations Sin:{}, Cos:{}, Tan:{}".format(sin,cos,tan))

Trignometric Operations Sin:[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]], Cos:[[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]], Tan:[[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]]


In [169]:
r1 = [[1.5678, 2.678], [3.678, 4.679]]
round1 = np.round(r1)
print("Round to nearest integer.", round1)


Round to nearest integer. [[2. 3.]
 [4. 5.]]


In [170]:
floor = np.floor(r1)
print("Rounds down to nearest whole number.",floor)

Rounds to nearest whole number. [[1. 2.]
 [3. 4.]]


In [172]:
ceil = np.ceil(r1)
print("Rounds up to the nearest whole number.",ceil)

Rounds up to the nearest whole number. [[2. 3.]
 [4. 5.]]


In [ ]:
# 5. Statistical Operations

In [177]:
mean = np.mean(r1)
print("Adds all value and divides by count.", mean)

Adds all value and divides by count. 3.1507


In [178]:
median = np.median(r1)
print("Average between middle values of flattened sorted array.",median)

Average between middle values of flattened sorted array. 3.178


In [192]:
sd1 = np.array([[2,4],[6,8]])
sd = np.std(sd1)
print("SD computation using Mean, Deviation and Variance calculation.",sd)

SD computation using Mean, Deviation and Variance calculation. 2.23606797749979


In [193]:
var = np.var(sd1)
print("Variance is the square of standard deviation.",var)

Variance is the square of standard deviation. 5.0


In [194]:
min = np.min(sd1)
max = np.max(sd1)
print("Minimum {} and Maximum {} value in the array".format(min, max))

Minimum 2 and Maximum 8 value in the array


In [195]:
percentile = np.percentile(sd1, 75)
print("75th percentile of Given array.", percentile)

75th percentile of Given array. 6.5


In [196]:
coefficient = np.corrcoef(sd1)
print("Correlation coefficient matrix between given array.",coefficient)

Correlation coefficient matrix between given array. [[1. 1.]
 [1. 1.]]


In [199]:
hist = np.histogram(sd1)
print("Histogram of given array",sd1)

Histogram of given array [[2 4]
 [6 8]]


In [204]:
argmax = np.argmax(sd1)
argmin = np.argmin(sd1)
print("Argmax Index of max value {} and Argmin index of min value  {} for the given array".format(argmax,argmin))

Argmax Index of max value 3 and Argmin index of min value  0 for the given array
