# I. Calculus

**1. Derivative**
Measures the rate at which a function changes at any point.

f'(x) = df(x)/dx

Manual Example:
Let f(x) = x**2
Then f'(x) = 2x
at x=3

f'(3) = 2x3 = 6



In [42]:
# Python Equivalent
import numpy as np
import matplotlib.pyplot as plt

def f(x):
    return x**2

def compute_derivative(f, x, h=1e-5):
  return (f(x + h) - f(x - h)) / (2 * h)

x=10
y = f(x)
derivative = compute_derivative(f, x)

print(f"The derivative of f(x) = x^2 at x = {x} is: {derivative:.4f}")

# Plot just the point and tangent line (no full curve)
plt.figure(figsize=(6, 4))
plt.scatter(x, y, color='red', s=50, label=f"Point ({x}, {y})")
# Tangent line: y = f(x) + derivative * (x_input - x)
plt.plot([2,12], [20,120], '--', color='blue', label=f"(slope = {derivative:.1f})")
# Annotate
plt.title(f"Derivative of $f(x) = x^2$ at $x = {x}$")
plt.xlabel("x")
plt.ylabel("f(x)")
plt.legend()
plt.grid(True)
plt.show()

The derivative of f(x) = x^2 at x = 10 is: 20.0000


**2. Partial Derivative**

Derivative of a multivariable function with respect to one variable.

Formula:

df(x,y)/dx , df(x,y)/dy

Manual Example:

  - Let f(x,y) = x**2 + y**2
  - df/dx = 2x, df/dy = 2y
  -- At x=1 and y=2
  -- df/dx=2, df/dy=4





In [50]:
# Python Equivalent
def f(x, y):
    return x**2 + y**3

def compute_partial_derivative(f, x, y, var='x', h=1e-5):
  if var == 'x':
    return (f(x + h, y) - f(x - h, y)) / (2 * h)
  else:
    return (f(x, y + h) - f(x, y - h)) / (2 * h)

x, y = 2.0, 3.0

df_dx = compute_partial_derivative(f, x, y, 'x')
df_dy = compute_partial_derivative(f, x, y, 'y')

print(f"∂f/∂x at ({x},{y}) = {df_dx:.4f}")
print(f"∂f/∂y at ({x},{y}) = {df_dy:.4f}")

∂f/∂x at (2.0,3.0) = 4.0000
∂f/∂y at (2.0,3.0) = 27.0000


**3. Gradient**

Vector of all partial derivatives — direction of steepest ascent.

∇f(x,y)=[∂f/∂x , ∂f/∂y]

Manual Example:
Same Function f(x,y) = x**2 + y**2
Gradient at x=2,y=3 is [4,6]






In [54]:
def f(x,y):
  return x**2 + y**2

def compute_gradient(f, x, y, h=1e-5):
  df_dx = (f(x + h, y) - f(x - h, y)) / (2 * h)
  df_dy = (f(x, y + h) - f(x, y - h)) / (2 * h)
  return np.array([df_dx, df_dy])

x, y = 2.0, 3.0
gradient = compute_gradient(f, x, y)
print(f"Gradient at ({x}, {y}): {gradient}")

Gradient at (2.0, 3.0): [4. 6.]


**4. Chain Rule**

The chain rule is one of the most important rules in calculus. It helps us compute the derivative of composite functions (functions inside other functions).

1. What is the Chain Rule?

If a variable z depends on y, and y depends on x, then z indirectly depends on x, and the derivative is:

dz/dx = dz/dy * dy/dx

2. Chain Rule Formula:

For a composite function: y = f(g(x))
Then the derivative of x is: dy/dx = df/dg * dg/dx

Or in function notation: d/dx[f(g(x))] = f'(g(x)) * g'(x)




In [55]:
import numpy as np

def f(x):
    return np.sin(x**2)

def f_prime(x):
    return np.cos(x**2) * 2 * x

x = 2
print(f"f({x}) =", f(x))
print("Derivative at x =", x, "is", f_prime(x))


f(2) = -0.7568024953079282
Derivative at x = 2 is -2.6145744834544478


# II. Probability & Statistics


**Mean(Expected Value)**
E(X)= ∑xi*pi

xi = Values
pi = Probabilities


In [2]:
import numpy as np
values = np.array([1,2,3])
probs = np.array([0.1, 0.2, 0.3])
mean = np.sum(values * probs)
print("Mean value", mean)

Mean value 1.4


**Variance & Standard Deviation:**

Variance = var(x) = E(x**2) - E(x)**2

E(X**2) = sum(Xi**2 * Pi)

E(x)**2 = sum(Xi * Pi)**2

std = sqrt(variance)




In [5]:
E_X2 = np.sum((values**2) * probs)
E_X = (np.sum(values * probs))**2
variance = E_X2 - E_X
std_deviation = np.sqrt(variance)
print("Variance", variance)
print("Standard Deviation", std_deviation)

Variance 1.64
Standard Deviation 1.2806248474865698


**Bayes Theorem:**

Bayes' Theorem helps us update the probability of an event based on new information.

P(A|B) = P(B|A) * P(A) / P(B)

P(A|B) = Probability of A happening given B (what we want to find).

P(B|A) = Probability of B happening given A.

P(A) =  Initial probability of A (prior belief).

P(B) = Total probability of B happening.

In [6]:
# Prior probabilities
P_jar1 = 0.5
P_jar2 = 0.5

# Likelihoods
P_cherry_given_jar1 = 0.7
P_cherry_given_jar2 = 0.4

# Total probability of picking a cherry (evidence)
P_cherry = (P_cherry_given_jar1 * P_jar1) + (P_cherry_given_jar2 * P_jar2)

# Bayes' Theorem: Posterior probability
P_jar1_given_cherry = (P_cherry_given_jar1 * P_jar1) / P_cherry

# Display result
print(f"Probability the cherry came from Jar 1: {P_jar1_given_cherry:.4f} or {P_jar1_given_cherry*100:.2f}%")



Probability the cherry came from Jar 1: 0.6364 or 63.64%


**Covariance Matrix:**

- Measures how two variables change together.

Formula:
  Cov(X, Y) = E[(X - E[X]) * (Y - E[Y])]



In [7]:
import numpy as np
cov_matrix = np.cov([[30, 50, 20], [60, 30, 10], [25, 45, 15]])  # 3 variables
print(cov_matrix)

[[233.33333333  83.33333333 233.33333333]
 [ 83.33333333 633.33333333  83.33333333]
 [233.33333333  83.33333333 233.33333333]]


**MEDIAN**
-----------------------------
- Middle value when sorted.

Example:

  [2, 3, 5], Median = 3

  [1, 2, 3, 4], Median = (2+3)/2 = 2.5

**MODE**
-----------------------------
- Most frequent value.

Example:

  [1, 2, 2, 3], Mode = 2

**RANGE**

- Difference between max and min.

Formula:
  Range = Max - Min

Example:
  [2, 6, 10], Range = 10 - 2 = 8

**Z-SCORE**
-----------------------------
- Number of standard deviations from the mean.

Formula:

  Z = (X - μ) / σ

Example:

  X = 85, Mean = 70, Std Dev = 10

  => Z = (85 - 70) / 10 = 1.5

# III. Optimization


**Gradient Descent**

Update rule to minimize cost.

Formula:

1. Compute the Cost function (Error value b/w predicted and original)
L(w) = (ytrue - ypred)**2

2. Update parameters:
θnew = θold - alpha * ∇J(θ)

θold = Old value
alpha = learning rate
∇J(θ) = Gradient (vector of partial derivatives) of the cost function J evaluated at the current parameter value θold.



In [8]:
# Objective: Minimize f(x) = x^2

def f(x):
    return x ** 2

def grad_f(x):
    return 2 * x  # Derivative of f(x) = x^2

# Initialize
x = 5             # Starting point
learning_rate = 0.1
epochs = 20       # How many steps

# Gradient Descent Loop
for i in range(epochs):
    grad = grad_f(x)
    x = x - learning_rate * grad
    print(f"Iteration {i+1}: x = {x:.4f}, f(x) = {f(x):.4f}")


Iteration 1: x = 4.0000, f(x) = 16.0000
Iteration 2: x = 3.2000, f(x) = 10.2400
Iteration 3: x = 2.5600, f(x) = 6.5536
Iteration 4: x = 2.0480, f(x) = 4.1943
Iteration 5: x = 1.6384, f(x) = 2.6844
Iteration 6: x = 1.3107, f(x) = 1.7180
Iteration 7: x = 1.0486, f(x) = 1.0995
Iteration 8: x = 0.8389, f(x) = 0.7037
Iteration 9: x = 0.6711, f(x) = 0.4504
Iteration 10: x = 0.5369, f(x) = 0.2882
Iteration 11: x = 0.4295, f(x) = 0.1845
Iteration 12: x = 0.3436, f(x) = 0.1181
Iteration 13: x = 0.2749, f(x) = 0.0756
Iteration 14: x = 0.2199, f(x) = 0.0484
Iteration 15: x = 0.1759, f(x) = 0.0309
Iteration 16: x = 0.1407, f(x) = 0.0198
Iteration 17: x = 0.1126, f(x) = 0.0127
Iteration 18: x = 0.0901, f(x) = 0.0081
Iteration 19: x = 0.0721, f(x) = 0.0052
Iteration 20: x = 0.0576, f(x) = 0.0033


**L2 Regularization**

Regularization is a technique used to prevent overfitting in machine learning models by discouraging overly complex models. It works by adding a "penalty" to the loss function to keep model weights (parameters) small.

Problem: A model with too many parameters may memorize training data (overfitting) instead of generalizing.

Solution: Regularization constrains the model to prefer simpler, smoother functions.

Regularization = Original Loss + Penalty

Total Cost=Original Loss+λ⋅Penalty
λ (lambda): Controls how strong the penalty is.
Penalty: Depends on the type of regularization.

**(1) L1 Regularization (Lasso)**

Loss L1 =Loss+ λ ∑∣wi∣

Adds a penalty proportional to the absolute values of weights.
Effect: Encourages sparsity (some weights become exactly 0).

**L2 Regularization (Ridge)**

J(θ)=Loss(θ)+λ∑θi2

Adds a penalty proportional to the squared values of weights.
Effect: Keeps weights small but rarely zero.

**Elastic Net (L1 + L2)**

Combines L1 and L2 penalties:

J(θ)=Loss(θ) + L1 + L2
